apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels: 
    name: nginx-service
spec:
  selector:
    environment: dev
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: label-1
  labels:
    app: nginx
    environment: dev
spec:
  containers:
  - name: label
    image: nginx