apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels: 
    name: nginx-service
    environment: DEV
spec:
  type: LoadBalancer
  selector:
    project: eksctl
    environment: dev
    componenet: nginx
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: eksctl
    environment: dev
    componenet: nginx
spec:
  containers:
  - name: nginx
    image: nginx